y-subtraction: 1 # How many blocks below the player the block check is for, generally keep at 1
log-cancels: true # If the plugin should log every mace cancel or not
developer-mode: false # Allows for creation of ghost blocks. When bedrock is placed, the block 2 under it will become a ghost block